/**
 * Generate typed contract bindings for the SDK from compiled forge
 * artifacts (contracts/out). Run after `arc-forge build`.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "contracts", "out");

function artifact(name: string) {
  const p = join(outDir, `${name}.sol`, `${name}.json`);
  const j = JSON.parse(readFileSync(p, "utf8"));
  return { abi: j.abi, bytecode: j.bytecode?.object as string };
}

const bounty = artifact("GapBounty");
const registry = artifact("EvidenceReceiptRegistry");
const mock = artifact("MockUSDC");

const ts = `// AUTO-GENERATED by scripts/build-abi.ts — do not edit.
// Regenerate: pnpm tsx scripts/build-abi.ts (after arc-forge build)
export const GAP_BOUNTY_ABI = ${JSON.stringify(bounty.abi, null, 2)} as const;
export const GAP_BOUNTY_BYTECODE = "${bounty.bytecode}" as const;
export const RECEIPT_REGISTRY_ABI = ${JSON.stringify(registry.abi, null, 2)} as const;
export const MOCK_USDC_ABI = ${JSON.stringify(mock.abi, null, 2)} as const;
export const MOCK_USDC_BYTECODE = "${mock.bytecode}" as const;
`;

const dest = join(root, "packages", "sdk", "src", "generated");
mkdirSync(dest, { recursive: true });
writeFileSync(join(dest, "contracts.ts"), ts);
console.log("wrote", join(dest, "contracts.ts"));
